export const DEV_COPY = {
  settingsLabel: "Developer mode",
  settingsToggle: "Bật Dev Mode",
  settingsHelp: "Hiển thị reasoning, tham số request, token usage và trace thao tác extension để phục vụ phát triển.",
  summaryPrefix: "DEV",
  request: "REQUEST",
  thinking: "THINKING",
  usage: "USAGE",
  unavailableUsage: "N/A — provider không gửi usage",
  thinkingNotReturned: "Provider không gửi reasoning.",
  copyThinking: "Sao chép reasoning",
  copied: "Đã sao chép",
  tool: "TOOL",
  status: "STATUS",
  metadataLabels: {
    extractor: "Trình trích xuất",
    contentChars: "Số ký tự",
    textLength: "Độ dài văn bản",
    warnings: "Cảnh báo",
    action: "Hành động",
    url: "URL",
    title: "Tiêu đề",
  } as Record<string, string>,
} as const;
